### ISSUE TITLE
Upgrade to vuetify 2.0.0

### ISSUE THREAD

**Issue by subdavis** [girder/girder_web_components#134]
Blocked on #111 probably.

**Comment by matthewma7** [comment]
My two cents, since the Vuetify release document suggests upgrading to Vuetify 1.5 first. Maybe we should do as suggested, sort out all slot usage that we have. Then upgrade to 2.0

**Comment by subdavis** [comment]
Agreed, should sort out our slot stuff before attempting this.

**Comment by subdavis** [comment]
I think it would be nice to make this a priority.  @matthewma7 do you think we need to chat to come up with a strategy for this and who will do what?  I don't have a great idea of how much effort it will be, but my impression is it won't be super easy.

Maybe we can divide up the components and each update half?

I think the vue slot syntax upgrade will be easier.

**Comment by waxlamp** [comment]
Just FYI, @jtomeck and I recently upgraded the Multinet client app to use Vuetify 2.0, in case we could somehow be of help here.

**Comment by subdavis** [comment]
@waxlamp how did you feel about it?  Straightforward and read the docs, or are there some gotchas we should be aware of?

**Comment by waxlamp** [comment]
It was a bit of a pain to adapt our build infrastructure to the newer way of installing Vuetify as a plugin, but that wasn't too bad. I don't know exactly what @jtomeck's experience was with updating the component usage itself, but IIRC it was fairly mechanical, if tedious.

**Comment by jeffbaumes** [comment]
I recently heard that @jourdain is making use of GWC. Seb, any concerns with moving this repo to Vuetify 2? It's the kind of thing where it makes sense for people to move together.

**Comment by jourdain** [comment]
I'm not ready yet, but we should definitely do it. I can still use an old package until I transition. 
But I think you should do it sooner rather that later especially if you have the cycle to do it now.

Also we should talk about small tweaks that could provide benefit in terms of usability. Especially since I'm starting to see some pattern emerge while working on HPCCloud while integrating several applications.

**Comment by jeffbaumes** [comment]
@jourdain, great, sounds like the path is clear to do this. I believe @subdavis and @matthewma7 would welcome suggestions for improvement via github issues or other discussions.

**Comment by jourdain** [comment]
Ok, I'll try to formalize it more in the coming days via a Google Doc, then maybe once shared we can plan for have an open discussion about it via hangout. What do you think?

**Comment by jourdain** [comment]
Initial quick and dirty pass on such [doc](https://docs.google.com/document/d/1tv6YkDFj8K1Hcx4_2jXkLiw3Z60qQ2gZQXWNuqwushM/edit?usp=sharing)

**Comment by subdavis** [comment]
@jourdain thanks!  do you have any specific feedback for GWC?   I think we could namespace the gwc icons to avoid conflicts with consumers.

**Comment by subdavis** [comment]
@matthewma7 FYI I've tried #111 and branch vue/2.6 and failed the same way in both places.   This will be blocked on #111, #152.

**Comment by jourdain** [comment]
Having std girder HTTP calls available in a module that can be used in a VueX store could be nice.

Other than that, I will really need to think about it more for your specific use case. I'm currently fighting issue when integrating full fleshed vue/vuetify app and hence my doc that I started.
But I know I may have some other idea for your components, it is just I can't think of any right now since the GWC integration was a while back and was mostly straight forward. Anyhow, it will end-up being small tweaks that would slightly reduce the integration complexity since that one is already pretty low which is great...

**Comment by subdavis** [comment]
Done in #154
