### ISSUE TITLE
Best practices

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder_web_components#16]
These are also a few meta comments on how we build components, each of which is up for approval or being shot down by the main developers of this repo.

These surfaced as I was implementing #15. 

1. We should use colors as intended by material design. If it is a primary action/toolbar use `color="primary"`, and if it is not anything special (like the "remove all" button) just use the default color. Vuetify has excellent support for themes if people don't want their apps to be all blue and gray.
1. We should avoid magic numbers wherever possible, which includes special padding and margin classes. The more we use them, the harder it is to make a consistent interface using mainly vuetify components.
1. Buttons should normally be an icon with a clear purpose or text, but not both, as seems to be standard in material design.
1. There are lots of slots in the widget. Should we be throwing in slots all over or should we have a clear (imminently needed or extremely obvious) use case for slots? Adding slots in the future shouldn't break compatibility, but removing them does, so we need to be careful about painting ourselves into a corner. For example, in #15 I removed a slot ("header") because I was reorganizing the UI, but that would be disallowed if the slot was in a release. I could have left the slot but it would be within another slot and would certainly break expected layout if people had been using the slot.

The repo in general is awesome. Very easy to set up and get running. Nice that there is an app that exposes the upload widget. Would be great if this app expands to a gallery of components when more are implemented.

**Comment by zachmullen** [comment]
> Nice that there is an app that exposes the upload widget. Would be great if this app expands to a gallery of components when more are implemented.

That's the plan

**Comment by zachmullen** [comment]
Responses to each point individually:

1. Agreed.
2. Agreed, although my experience so far with Vuetify leads me to believe we'll still see plenty of the Vuetify margin and padding classes for any non-trivial components. One hard and fast rule we should make is that a component's top-level element should not have any margin or padding applied; those classes should only ever be used to separate *internal* elements of a component.

My rationale for being OK with these classes is twofold: for one, we won't be able to use prebaked Vuetify components for everything. It provides a lot, but it's not designed to accommodate *all* the things we'll want to do, and that's OK. Secondly, the special classes provided by Vuetify for margin and padding are in fact part of its API, if you will, and furthermore they are part of Material Design (which is why there is a small discrete set of available sizes). In that way, they're akin to the typography classes and theme colors exposed in Vuetify.

All that said, we should avoid using them gratuitously.

3. Agreed. I'd like to hear @jtomeck 's thoughts on when to use which one, and whether mixing them in the same app is reasonable.

4. We definitely shouldn't go too crazy with the slots, and I'm happy to pare them down. A slot provides strictly more value than just a boolean display property for a subcomponent, but we again don't want to add them gratuitously. A reasonable policy might be to only add slots for switches we added to the corresponding widgets in the old Backbone client, or where we have existing or anticipated use cases for ongoing projects.

**Comment by jbeezley** [comment]
I'm comfortable with having slots as long as they are for a well defined portion of the UI.  I think the only reason why we would want to remove a slot is if we had any larger-scale reorganization of the component.  Something like that should should come in the form of a major version/new component anyway.

By themselves, slots are very isolated--in that they don't have access to the component's data.  In many cases, if downstreams want to do anything with the slots, they will want to make them scoped to pass data.  This is where we should proceed with caution.  As an example, the [files slot](https://github.com/girder/girder_web_components/blob/master/src/components/Upload.vue#L48) in the upload component is mostly useless as is.  To make it useful, one would need to pass the `files` array into the slot, but that starts exposing the internal state.

I think Vuetify's [data-table](https://vuetifyjs.com/en/components/data-tables) component is a good example of going too far with scoped slots and general customizeability to the point of making it hard to use.

**Comment by jtomeck** [comment]
@zachmullen - I think many times in our applications the icon falls short on letting the user know what the button's purpose is. I think that if we use only an icon we at least should have a tooltip paired with it. I think mixing them in the same app is acceptable. I think a general rule is if it's a button in a toolbar, or something similar, go icon with tooltip. If it's a lone button to perform an action such as a submit button use an actual button with icon and text or just text.

**Comment by jeffbaumes** [comment]
Note that on 3), I may have spoken too soon. There are [examples and standards](https://material.io/design/components/buttons.html) for buttons with icon plus text.

What seemed wrong in the upload widget is that a magic padding number was added, which made it seem nonstandard. But Vuetify does offer icon flags to add padding automatically (`left` and `right`), see [this example](https://codepen.io/anon/pen/gdQzXa?&editors=111). Something like this would be a preferred method if we do use icon and text in buttons, not leaving room for inconsistencies.

What probably matters most is to have consistency within an app, so Girder should decide when and where to utilize icon plus text, if at all.

**Comment by zachmullen** [comment]
I'm going to close this since it isn't actionable, feel free to continue the discussion though, or to open an actionable issue e.g. "add best practices docs".
