### ISSUE TITLE
Using createLocalVue in testing causes errors

### ISSUE THREAD

**Issue by zachmullen** [girder/girder_web_components#32]
The Vue component tests that use vue-test-utils' `createLocalVue` function emit console error messages, even though they pass:

```
console.error node_modules/vuetify/dist/vuetify.js:20347
    [Vuetify] Multiple instances of Vue detected
    See https://github.com/vuetifyjs/vuetify/issues/4068
    
    If you're seeing "$attrs is readonly", it's caused by this
```

I think this happens because our code (e.g. RestClient) imports the global Vue. I would consider this a warning rather than an error, in that it isn't an error right now, but could lead to them in the future.[Here](https://vue-test-utils.vuejs.org/guides/common-tips.html#applying-global-plugins-and-mixins) are the docs about using this, from reading that it seems like we don't really need to use createLocalVue, so the simplest solution might just be not to use it.

As part of any fix for this issue, we should probably create a helper function for our testing that returns an appropriate Vue instance that can be passed as `localVue`, and has the GirderVue plugin installed (depends on #30).

**Comment by jbeezley** [comment]
Vuetify is the culprit here.  Its [install method](https://github.com/vuetifyjs/vuetify/blob/dev/src/components/Vuetify/index.ts#L24) checks against the global Vue object to see if two different Vue libraries have been imported.  In a normal application that would work, but it causes a false positive in testing.

What we are doing in `rest.js` is shouldn't be an issue at least for people using vue-cli 3... It aliases the Vue symbol to that which is installed by the application.

Looks like there is no way to avoid the warning without using global vue everywhere in testing until they fix the issue.  We *could* do that, but there is no particular reason we should have to.

**Comment by subdavis** [comment]
Behavior was changed in #36 to use global vue in testing.

**Comment by vladyn** [comment]
Thanks for that clarification @jbeezley! I had this annoying warning in my tests.
